### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by tyrw** [cloudinary/cloudinary_angular#18] opened 2015-01-29 18:12 UTC
I'd love to drop this into our project, but the dependency on jQuery is a deal-killer since we're keeping things as light as possible.  

We (and I assume many others) would find it pretty valuable to have cloudinary as a standalone bower install to get up to speed more quickly.

**Comment by julianfox** [comment] 2015-02-11 13:50
+1 same for us...

**Comment by taragano** [comment] 2015-02-13 01:17
It's on our road-map to support a jQuery-free solution for our Angular client library.
We'll let you know of any updates.

**Comment by ArdentKid** [comment] 2015-04-29 06:33
+1

**Comment by azachar** [comment] 2015-05-02 21:25
+1

**Comment by websirnik** [comment] 2015-06-08 12:19
+1

**Comment by paulogr** [comment] 2015-07-06 02:45
+1

**Comment by xaralis** [comment] 2015-07-22 09:06
Yes! For us, it would be perfectly possible to even live with jQuery as dependency, but the problem is with all other dependencies it introduces - blueimp-file-upload in particular. The only thing from your jQuery cloudinary-js lib used here is `cloudinary.url()` function. Please, port it... thanks.

**Comment by tinusn** [comment] 2015-08-21 07:59
I created a version with no depency on jquery, get it here [cloudinary-angular](https://github.com/tinusn/cloudinary-angular). Please note that it does not include all directives.

**Comment by tocker** [comment] 2016-02-24 00:26
As of version 0.2.0 the library does not depend on jQuery.

**Comment by strausr** [comment] 2019-11-24 10:14
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by strausr** 2019-11-24 10:14 UTC
Labels: enhancement
