### ISSUE TITLE
Issue while upgrade @cloudinary/angular to @cloudinary/angular-5.x

### ISSUE THREAD

**Issue by mohdalixotiv** [cloudinary/cloudinary_angular#137] opened 2018-03-08 14:55 UTC
when I update @cloudinary/angular to @cloudinary/angular-5.x. error coming as:

![image](https://user-images.githubusercontent.com/36029075/37157148-03fef81c-230e-11e8-8482-2a577f118030.png)

ionic info are as:

![image](https://user-images.githubusercontent.com/36029075/37157223-3f6e15cc-230e-11e8-9ffe-c67500774484.png)

Any help will be appriciable. Thanks in advance.

**Comment by strausr** [comment] 2018-03-08 17:05
@mohdalixotiv Can you please specify what version you upgraded from and what version of typescript are you using?

**Comment by mohdalixotiv** [comment] 2018-03-09 07:07
**Privios Versions**: Angular 4.1.3 Ionic 3.0.1
**Current Versions**: Angular 5.2.7 Ionic 3.9.2

**Comment by strausr** [comment] 2018-03-09 08:38
@mohdalixotiv We're unable to reproduce this error. If you're still experiencing errors, please share with us a project that reproduces the errors. You can also share your project via a support ticket at support@cloudinary.com

**Comment by strausr** [comment] 2018-03-09 09:30
@mohdalixotiv Can you please specify the TypeScript versions you're using and if it was updated as well?

**Comment by mohdalixotiv** [comment] 2018-03-09 10:20
previos typescript version: 2.2.2 now 2.3.4

**Comment by strausr** [comment] 2018-03-13 13:49
@mohdalixotiv Looks like the issue is with the typescript version. Please upgrade to a version >=2.4.x

**Comment by roeeba** [comment] 2018-09-13 14:55
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2018-09-13 14:55 UTC
Labels: question
